"""Shared pytest fixtures.

Backend tests run against a temporary SQLite database — sufficient because
all DDL is generated by SQLAlchemy. Adapter calls are mocked via mode='mock'.
"""

from __future__ import annotations

import base64
import os
from collections.abc import Iterator

import pytest

# Ensure env vars are present before any app import.
os.environ.setdefault("APP_ENV", "local")
os.environ.setdefault("SECRET_KEY", "test-" + "x" * 40)
os.environ.setdefault("DATABASE_URL", "sqlite+pysqlite:///./test.db")
os.environ.setdefault("REDIS_URL", "redis://localhost:6379/0")
os.environ.setdefault("CELERY_BROKER_URL", "redis://localhost:6379/1")
os.environ.setdefault("CELERY_RESULT_BACKEND", "redis://localhost:6379/2")
os.environ.setdefault("S3_ENDPOINT_URL", "http://localhost:9000")
os.environ.setdefault("S3_ACCESS_KEY", "x")
os.environ.setdefault("S3_SECRET_KEY", "x")
os.environ.setdefault("S3_BUCKET", "test")
os.environ.setdefault(
    "FIELD_ENCRYPTION_KEY",
    "base64:" + base64.b64encode(b"0" * 32).decode(),
)

from app import database as db_module
from app.main import app
from app.models import Base
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker


@pytest.fixture(scope="session")
def engine():
    eng = create_engine("sqlite+pysqlite:///:memory:", future=True)
    Base.metadata.create_all(eng)
    return eng


@pytest.fixture
def db_session(engine, monkeypatch) -> Iterator:
    """Per-test session with rollback isolation."""
    session_factory = sessionmaker(
        bind=engine, autoflush=False, autocommit=False, expire_on_commit=False
    )
    monkeypatch.setattr(db_module, "SessionLocal", session_factory)
    monkeypatch.setattr(db_module, "engine", engine)
    session = session_factory()
    try:
        yield session
    finally:
        session.close()


@pytest.fixture
def client(db_session) -> TestClient:
    return TestClient(app)
